#ifndef DATATYPES_H
#define DATATYPES_H

enum Datatype{
    ELECTRICITY_CONSUMPTION,
    ELECTRICITY_CONSUMPTION_FORECAST,
    ELECTRICITY_PRODUCTION_FORECAST,
    ELECTRICITY_PRODUCTION,
    WIND_POWER_PRODUCTION_FORECAST,
    NUCLEAR_POWER_PRODUCTION,
    HYDRO_POWER_PRODUCTION,
    POWER_FORMS_PERCENTAGES,
    TEMPERATURE,
    OBSERVED_WIND,
    OBSERVED_CLOUDINESS,
    PREDICTED_WIND,
    PREDICTED_TEMPERATURE
};

#endif // DATATYPES_H
