#ifndef DATAMANAGER_H
#define DATAMANAGER_H

#include <QObject>
#include <memory>
#include <vector>
#include "data.hh"

/**
 * @brief The DataManager class is used to store Data objects and make read and write
 * operations to store the Data objects in a file.
 */
class DataManager : public QObject
{
    Q_OBJECT
public:
    explicit DataManager(QObject *parent = nullptr);

public slots:

    /**
     * @brief addData stores the given data object in data_ map
     * @param data
     */
    void addData(std::shared_ptr<Data> data);

    /**
     * @brief saveDataToFile saves data object to a json file
     * @param filename : name of the file (without file extension)
     * @param path : path to the folder where to store the file
     * the format of the path is file:///path
     * @param id : id of the data to be saved
     */
    void saveDataToFile(QString filename, QString path, QString id);

    /**
     * @brief loadDataFromFile loads and creates a data object from json file
     * @param filepath : path of the file where to store the file
     * the format of the path is file:///path
     */
    void loadDataFromFile(QString filepath);

    /**
     * @brief savePrefToFile saves user preferences to a json file
     * @param filename : name of the file (without file extension)
     * @param path : path to the folder where the file is stored
     * the format of the path is file:///path
     * @param id : id of the preference saved
     */
    void savePrefToFile(QString filename, QString path);

    /**
     * @brief loadPrefFromFile : loads a json file and makes an api-call with the preference data
     * @param filepath : path of the file
     * the format of the path is file:///path
     */
    void loadPrefFromFile(QString filepath);

    /**
     * @brief toJSONPref goes through data_ map and converts
     * all the datas into one preference file format.
     * @return returns a QJsonDocument that holds the preferences
     */
    QJsonDocument toJSONPref();

    /**
     * @brief removeData removes data object from the data_ map
     * @param id of the data to be removed
     */
    void removeData(QString& id);

signals:

    /**
     * @brief dataAdded forwards the data that was added to the data_ map
     * @param data
     */
    void dataAdded(std::shared_ptr<Data> data);

    /**
     * @brief prefLoaded forwards a preference that was loaded from a file
     * @param pref a QJsonObject that defines one preference
     */
    void prefLoaded(QJsonObject pref);

    /**
     * @brief error signals an error message generated by the DataManager object
     * @param error
     */
    void error(QString error);

private:
    std::map<QString,std::shared_ptr<Data>> data_;

};

#endif // DATAMANAGER_H
